<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class OrderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $orders = [
            [
                'order_id' => 'ORD-2024-001',
                'product_name' => 'Merino Wool Sweater',
                'size' => 'XL',
                'wool_color' => 'Charcoal',
                'weight' => 1.8,
                'total_quantity' => 25,
                'due_date' => Carbon::now()->addDays(45),
                'status' => 'pending',
                'wages_per_unit' => 250.00,
                'notes' => 'Premium merino wool, hand-knitted',
                'notification_channel' => 'email',
                'notification_id' => null,
                'notified_at' => null,
                'product_photo' => null,
                'client_name' => 'Luxury Boutique',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'ORD-2024-002',
                'product_name' => 'Alpaca Wool Scarf',
                'size' => '180x70cm',
                'wool_color' => 'Camel',
                'weight' => 0.8,
                'total_quantity' => 40,
                'due_date' => Carbon::now()->addDays(30),
                'status' => 'in_production',
                'wages_per_unit' => 180.00,
                'notes' => 'Luxury alpaca wool, reversible design',
                'notification_channel' => 'sms',
                'notification_id' => 'SMS-789012',
                'notified_at' => Carbon::now()->subDays(2),
                'product_photo' => null,
                'client_name' => 'Winter Essentials',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'ORD-2024-003',
                'product_name' => 'Cashmere Blanket',
                'size' => '200x200cm',
                'wool_color' => 'Ivory',
                'weight' => 2.2,
                'total_quantity' => 15,
                'due_date' => Carbon::now()->addDays(60),
                'status' => 'pending',
                'wages_per_unit' => 350.00,
                'notes' => '100% pure cashmere, hand-finished edges',
                'notification_channel' => 'email',
                'notification_id' => null,
                'notified_at' => null,
                'product_photo' => null,
                'client_name' => 'Home Luxury',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'ORD-2024-004',
                'product_name' => 'Wool Socks Set',
                'size' => 'M',
                'wool_color' => 'Navy',
                'weight' => 0.4,
                'total_quantity' => 100,
                'due_date' => Carbon::now()->addDays(20),
                'status' => 'dispatched',
                'wages_per_unit' => 80.00,
                'notes' => '3 pairs set, merino wool blend',
                'notification_channel' => 'email',
                'notification_id' => 'EMAIL-345678',
                'notified_at' => Carbon::now()->subDays(5),
                'product_photo' => null,
                'client_name' => 'Sock Haven',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'ORD-2024-005',
                'product_name' => 'Angora Wool Beanie',
                'size' => 'One Size',
                'wool_color' => 'Burgundy',
                'weight' => 0.3,
                'total_quantity' => 50,
                'due_date' => Carbon::now()->addDays(15),
                'status' => 'in_production',
                'wages_per_unit' => 120.00,
                'notes' => 'Soft angora blend, pom-pom detail',
                'notification_channel' => 'sms',
                'notification_id' => 'SMS-901234',
                'notified_at' => Carbon::now()->subDays(1),
                'product_photo' => null,
                'client_name' => 'Accessories Plus',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'ORD-2024-006',
                'product_name' => 'Wool Gloves',
                'size' => 'L',
                'wool_color' => 'Forest Green',
                'weight' => 0.5,
                'total_quantity' => 75,
                'due_date' => Carbon::now()->addDays(25),
                'status' => 'pending',
                'wages_per_unit' => 90.00,
                'notes' => 'Touchscreen compatible, merino wool',
                'notification_channel' => 'email',
                'notification_id' => null,
                'notified_at' => null,
                'product_photo' => null,
                'client_name' => 'Winter Gear Co.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 'ORD-2024-007',
                'product_name' => 'Wool Poncho',
                'size' => 'One Size',
                'wool_color' => 'Rust',
                'weight' => 1.5,
                'total_quantity' => 30,
                'due_date' => Carbon::now()->addDays(40),
                'status' => 'in_production',
                'wages_per_unit' => 200.00,
                'notes' => 'Hand-woven, geometric pattern',
                'notification_channel' => 'sms',
                'notification_id' => 'SMS-567890',
                'notified_at' => Carbon::now()->subDays(3),
                'product_photo' => null,
                'client_name' => 'Boho Style',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('orders')->insert($orders);
    }
}
