<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class OrderAssignmentTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $assignments = [
            [
                'order_id' => 1,
                'artisan_id' => 1,
                'assigned_quantity' => 10,
                'completed_quantity' => 8,
                'approved_quantity' => 7,
                'rejected_quantity' => 1,
                'approved_at' => Carbon::now()->subDays(2),
                'approved_by' => 1,
                'dispatched_at' => Carbon::now()->subDay(),
                'dispatched_by' => 1,
                'dispatch_date' => Carbon::now()->subDay(),
                'dispatch_method' => 'courier',
                'dispatch_notes' => 'Delivered via Express Courier',
                'status' => 'dispatched',
                'rejection_reason' => 'Quality check failed - uneven stitching',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 2,
                'artisan_id' => 2,
                'assigned_quantity' => 20,
                'completed_quantity' => 15,
                'approved_quantity' => 15,
                'rejected_quantity' => 0,
                'approved_at' => Carbon::now()->subDays(5),
                'approved_by' => 1,
                'dispatched_at' => Carbon::now()->subDays(3),
                'dispatched_by' => 1,
                'dispatch_date' => Carbon::now()->subDays(3),
                'dispatch_method' => 'pickup',
                'dispatch_notes' => 'Client picked up in person',
                'status' => 'dispatched',
                'rejection_reason' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 3,
                'artisan_id' => 3,
                'assigned_quantity' => 8,
                'completed_quantity' => 5,
                'approved_quantity' => 0,
                'rejected_quantity' => 0,
                'approved_at' => null,
                'approved_by' => null,
                'dispatched_at' => null,
                'dispatched_by' => null,
                'dispatch_date' => null,
                'dispatch_method' => null,
                'dispatch_notes' => null,
                'status' => 'in_production',
                'rejection_reason' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 4,
                'artisan_id' => 4,
                'assigned_quantity' => 15,
                'completed_quantity' => 15,
                'approved_quantity' => 12,
                'rejected_quantity' => 3,
                'approved_at' => Carbon::now()->subDays(1),
                'approved_by' => 1,
                'dispatched_at' => null,
                'dispatched_by' => null,
                'dispatch_date' => null,
                'dispatch_method' => null,
                'dispatch_notes' => null,
                'status' => 'approved',
                'rejection_reason' => 'Size variation in 3 pieces',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 5,
                'artisan_id' => 5,
                'assigned_quantity' => 12,
                'completed_quantity' => 10,
                'approved_quantity' => 0,
                'rejected_quantity' => 0,
                'approved_at' => null,
                'approved_by' => null,
                'dispatched_at' => null,
                'dispatched_by' => null,
                'dispatch_date' => null,
                'dispatch_method' => null,
                'dispatch_notes' => null,
                'status' => 'pending',
                'rejection_reason' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 6,
                'artisan_id' => 1,
                'assigned_quantity' => 25,
                'completed_quantity' => 20,
                'approved_quantity' => 18,
                'rejected_quantity' => 2,
                'approved_at' => Carbon::now()->subDays(3),
                'approved_by' => 1,
                'dispatched_at' => Carbon::now()->subDays(1),
                'dispatched_by' => 1,
                'dispatch_date' => Carbon::now()->subDays(1),
                'dispatch_method' => 'courier',
                'dispatch_notes' => 'Standard delivery',
                'status' => 'dispatched',
                'rejection_reason' => 'Material quality issues in 2 pieces',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'order_id' => 7,
                'artisan_id' => 2,
                'assigned_quantity' => 10,
                'completed_quantity' => 8,
                'approved_quantity' => 0,
                'rejected_quantity' => 0,
                'approved_at' => null,
                'approved_by' => null,
                'dispatched_at' => null,
                'dispatched_by' => null,
                'dispatch_date' => null,
                'dispatch_method' => null,
                'dispatch_notes' => null,
                'status' => 'in_production',
                'rejection_reason' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('order_assignments')->insert($assignments);
    }
}
