<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PettyCashCategoryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Cash on Hand',
                'type' => 'asset',
                'description' => 'Physical cash available for immediate use',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kitchen Expenses',
                'type' => 'expense',
                'description' => 'Expenses related to kitchen operations and supplies',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Water',
                'type' => 'expense',
                'description' => 'Water utility expenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fuel',
                'type' => 'expense',
                'description' => 'Fuel expenses for vehicles and equipment',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hospitality',
                'type' => 'expense',
                'description' => 'Entertainment and hospitality expenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Production Supplies',
                'type' => 'expense',
                'description' => 'Supplies used in production processes',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Repair and Maintenance',
                'type' => 'expense',
                'description' => 'Expenses for repairing and maintaining equipment and facilities',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fixed Assets',
                'type' => 'asset',
                'description' => 'Long-term assets like equipment and property',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Wages',
                'type' => 'expense',
                'description' => 'Payment for hourly or daily workers',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Advance',
                'type' => 'expense',
                'description' => 'Money given in advance to employees or for projects',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Salary',
                'type' => 'expense',
                'description' => 'Regular payment to salaried employees',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Office Expenses',
                'type' => 'expense',
                'description' => 'General office operational expenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stationery',
                'type' => 'expense',
                'description' => 'Office stationery and supplies',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Advance Return',
                'type' => 'income',
                'description' => 'Money returned from previously given advances',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Performance Appraisal',
                'type' => 'expense',
                'description' => 'Expenses related to employee performance evaluation',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Advance Amount',
                'type' => 'expense',
                'description' => 'Amount given as advance to employees or for projects',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Current Assets',
                'type' => 'asset',
                'description' => 'Short-term assets that can be converted to cash within a year',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Office Supplies',
                'type' => 'expense',
                'description' => 'General office supplies like paper, pens, and stationery',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maintenance',
                'type' => 'expense',
                'description' => 'Equipment and facility maintenance expenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Transportation',
                'type' => 'expense',
                'description' => 'Local travel and transportation expenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Utilities',
                'type' => 'expense',
                'description' => 'Electricity, water, and other utility payments',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Refreshments',
                'type' => 'expense',
                'description' => 'Coffee, tea, and other refreshments for staff',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cleaning Supplies',
                'type' => 'expense',
                'description' => 'Cleaning materials and janitorial supplies',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Postage',
                'type' => 'expense',
                'description' => 'Postal services and courier expenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Miscellaneous',
                'type' => 'expense',
                'description' => 'Other miscellaneous expenses not covered by other categories',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reimbursement',
                'type' => 'income',
                'description' => 'Employee reimbursements for business expenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Refund',
                'type' => 'income',
                'description' => 'Refunds from suppliers or vendors',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sale of Scrap',
                'type' => 'income',
                'description' => 'Income from selling scrap materials',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Emergency Fund',
                'type' => 'expense',
                'description' => 'Emergency and contingency expenses',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Training Materials',
                'type' => 'expense',
                'description' => 'Training and educational materials for staff',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'First Aid Supplies',
                'type' => 'expense',
                'description' => 'Medical and first aid supplies for the workplace',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Security Services',
                'type' => 'expense',
                'description' => 'Security-related expenses and services',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('petty_cash_categories')->insert($categories);
    }
}
